name: Update flake.lock

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          pr-title: "chore(deps): update flake.lock"
          pr-labels: dependencies
          commit-msg: "chore(deps): update flake.lock"
