name: Update flake.lock

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          pr-title: "chore(deps): update flake.lock"
          pr-labels: dependencies
          commit-msg: "chore(deps): update flake.lock"
